SELECT TOP 10 SB1.B1_COD, LTRIM(RTRIM(SB1.B1_DESC)), SB1.B1_MSBLQL,
       SB1.B1_UM, SB1.B1_XNOMMAR, SB1.B1_PROC, 
       SA2.A2_NOME AS NOME_FORNECEDOR,  -- Incluindo o nome do fornecedor
	   SB1.B1_XCAT1,
	  -- ZZ3.ZZ3_DESCR AS DESCRICAO_CATEGORIA, -- Incluindo a descrição da categoria
	   SB1.B1_XCAT2,
	  -- ZZ4.ZZ4_DESCR AS DESCRICAO_SUBGRUPO1, -- Incluindo a descrição do SUBGRUPO 1
	   SB1.B1_XGRP1,
	  -- ZZ1.ZZ1_DESCR AS DESCRICAO_SUBGRUPO2, -- Incluindo a descrição do SUBGRUPO 2
	   SB1.B1_XGRP2,
	  -- ZZ2.ZZ2_DESCR AS DESCRICAO_SUBGRUPO3, -- Incluindo a descrição do SUBGRUPO 3
       SB1.B1_DESBSE3, SB1.B1_XIDPATR, 
       SB1.B1_PESO, SB1.B1_POSIPI, SB1.B1_XCULQBR,
       SB1.B1_XNOMUNI, 
	   ISNULL(CONVERT(VARCHAR(5000), SB1.B1_XPRATIV), '') AS B1_XPRATIV,  -- Conversão do campo B1_XPRATIV
	   SB1.B1_XCONCET,
       SB1.B1_XCODANT, SB1.B1_XAPRES, SB1.B1_IDSAN01,
       SB1.B1_XIDSAN0, SB1.B1_XIDSAN3
FROM [1_RAW].[SB1_PROTHEUS] SB1
LEFT JOIN [1_RAW].[SA2_PROTHEUS] SA2 ON SB1.B1_PROC = SA2.A2_COD  -- Ajustado o JOIN para a tabela
--LEFT JOIN [1_RAW].[ZZ3_PROTHEUS] ZZ3 ON SB1.B1_XCAT1 = ZZ3.ZZ3_COD
--LEFT JOIN [1_RAW].[ZZ4_PROTHEUS] ZZ4 ON SB1.B1_XCAT2 = ZZ4.ZZ4_COD
--LEFT JOIN [1_RAW].[ZZ1_PROTHEUS] ZZ1 ON SB1.B1_XGRP1 = ZZ1.ZZ1_COD
--LEFT JOIN [1_RAW].[ZZ2_PROTHEUS] ZZ2 ON SB1.B1_XGRP2 = ZZ2.ZZ2_COD
WHERE SB1.B1_COD > '26179'
AND SB1.B1_MSBLQL = '2'
ORDER BY SB1.B1_COD ASC;
