SELECT
    LTRIM(RTRIM(SB1.B1_COD)) AS B1_COD, 
    LTRIM(RTRIM(SB1.B1_DESC)) AS B1_DESC,
    LTRIM(RTRIM(SB1.B1_XCAT1)) AS B1_XCAT1,
    LTRIM(RTRIM(ZZ3.ZZ3_DESCR)) AS DESCRICAO_CATEGORIA,  -- Descrição da categoria
    LTRIM(RTRIM(SB1.B1_XCAT2)) AS B1_XCAT2,
    LTRIM(RTRIM(ZZ4.ZZ4_DESCR)) AS DESCRICAO_SUBGRUPO1,  -- Descrição do Subgrupo 1
    LTRIM(RTRIM(SB1.B1_XGRP1)) AS B1_XGRP1,
    LTRIM(RTRIM(ZZ1.ZZ1_DESCR)) AS DESCRICAO_SUBGRUPO2,  -- Descrição do Subgrupo 2
    LTRIM(RTRIM(SB1.B1_XGRP2)) AS B1_XGRP2,
    LTRIM(RTRIM(ZZ2.ZZ2_DESCR)) AS DESCRICAO_SUBGRUPO3,  -- Descrição do Subgrupo 3
    LTRIM(RTRIM(SB1.B1_XCULQBR)) AS CULTURA_QBR,
    LTRIM(RTRIM(SB1.B1_IDSAN01)) AS GRUPO_QBR,
	    CASE 
        WHEN LTRIM(RTRIM(SB1.B1_IDSAN01)) = '01' THEN 'HERBICIDA PASTAGEM'
        WHEN LTRIM(RTRIM(SB1.B1_IDSAN01)) = '02' THEN 'HERBICIDA AGRICOLA'
        WHEN LTRIM(RTRIM(SB1.B1_IDSAN01)) = '03' THEN 'SEMENTES'
        WHEN LTRIM(RTRIM(SB1.B1_IDSAN01)) = '04' THEN 'NUTRICAO ANIMAL'
        WHEN LTRIM(RTRIM(SB1.B1_IDSAN01)) = '05' THEN 'FERRAGENS E FERRAMENTAS'
        WHEN LTRIM(RTRIM(SB1.B1_IDSAN01)) = '06' THEN 'ADUBOS, FERTILIZANTES E CORRETIVOS'
		WHEN LTRIM(RTRIM(SB1.B1_IDSAN01)) = '07' THEN 'INSETICIDAS'
		WHEN LTRIM(RTRIM(SB1.B1_IDSAN01)) = '08' THEN 'ADJUVANTE'
		WHEN LTRIM(RTRIM(SB1.B1_IDSAN01)) = '09' THEN 'SAUDE ANIMAL'
        ELSE 'OUTROS'
    END AS CATEGORIA
FROM [1_RAW].[SB1_PROTHEUS] SB1
LEFT JOIN 
    [1_RAW].[ZZ3_PROTHEUS] ZZ3 
    ON LTRIM(RTRIM(SB1.B1_XCAT1)) = LTRIM(RTRIM(ZZ3.ZZ3_COD))
LEFT JOIN 
    [1_RAW].[ZZ4_PROTHEUS] ZZ4 
    ON LTRIM(RTRIM(SB1.B1_XCAT1)) = LTRIM(RTRIM(ZZ4.ZZ4_CAT1))  
    AND LTRIM(RTRIM(SB1.B1_XCAT2)) = LTRIM(RTRIM(ZZ4.ZZ4_COD))
LEFT JOIN 
    [1_RAW].[ZZ1_PROTHEUS] ZZ1 
    ON LTRIM(RTRIM(SB1.B1_XCAT1)) = LTRIM(RTRIM(ZZ1.ZZ1_CAT1))  
    AND LTRIM(RTRIM(SB1.B1_XCAT2)) = LTRIM(RTRIM(ZZ1.ZZ1_CAT2)) 
    AND LTRIM(RTRIM(SB1.B1_XGRP1)) = LTRIM(RTRIM(ZZ1.ZZ1_COD))
LEFT JOIN 
    [1_RAW].[ZZ2_PROTHEUS] ZZ2 
    ON LTRIM(RTRIM(SB1.B1_XCAT1)) = LTRIM(RTRIM(ZZ2.ZZ2_CAT1))  
    AND LTRIM(RTRIM(SB1.B1_XCAT2)) = LTRIM(RTRIM(ZZ2.ZZ2_CAT2)) 
    AND LTRIM(RTRIM(SB1.B1_XGRP1)) = LTRIM(RTRIM(ZZ2.ZZ2_GRP)) 
    AND LTRIM(RTRIM(SB1.B1_XGRP2)) = LTRIM(RTRIM(ZZ2.ZZ2_COD))
ORDER BY B1_COD;
