SELECT * FROM [1_RAW].[ZZ3_PROTHEUS] -- CATEGORIA 

SELECT * FROM [1_RAW].[ZZ4_PROTHEUS] -- SUBGRUPO 1

SELECT * FROM [1_RAW].[ZZ1_PROTHEUS] -- SUBGRUPO 2

SELECT * FROM [1_RAW].[ZZ2_PROTHEUS] -- SUBGRUPO 3





