WITH DadosOrdenados AS (
	SELECT B1_XPRATIV, B1_COD, B1_DESC, 
B1_XCAT1, ZZ3_DESCR AS CATEGORIA,
B1_XCAT2, ZZ4_DESCR AS SUBGRUPO1, 
B1_XGRP1, ZZ1_DESCR AS SUBGRUPO2, 
B1_XGRP2, ZZ1_DESCR AS SUBGRUPO3,
ROW_NUMBER() OVER (PARTITION BY B1_COD ORDER BY B1_DESC) AS RN
FROM [1_RAW].[SB1_PROTHEUS]
	LEFT JOIN
		[1_RAW].[ZZ3_PROTHEUS]
		ON B1_XCAT1 = ZZ3_COD
	LEFT JOIN
		[1_RAW].[ZZ4_PROTHEUS]
		ON B1_XCAT1 = ZZ3_COD
		AND B1_XCAT2 = ZZ4_COD
	LEFT JOIN
		[1_RAW].[ZZ1_PROTHEUS]
		ON B1_XCAT1 = ZZ3_COD
		AND B1_XCAT2 = ZZ4_COD
		AND B1_XGRP1 = ZZ1_COD
	LEFT JOIN
		[1_RAW].[ZZ2_PROTHEUS]
		ON B1_XCAT1 = ZZ3_COD
		AND B1_XCAT2 = ZZ4_COD
		AND B1_XGRP1 = ZZ1_COD
		AND B1_XGRP2 = ZZ2_COD
	WHERE B1_XCAT1 = 09
	AND B1_XPRATIV IS NULL OR B1_XPRATIV = ''
)
SELECT
	B1_XPRATIV, B1_COD, B1_DESC, B1_XCAT1, CATEGORIA, B1_XCAT2, SUBGRUPO1, B1_XGRP1, SUBGRUPO2, B1_XGRP2, SUBGRUPO3
FROM DadosOrdenados
WHERE RN = 1
	ORDER BY B1_DESC