SELECT SD1.D1_COD, SD1.D1_FILIAL
FROM [1_RAW].[SD1_PROTHEUS] SD1
WHERE 
    SD1.D_E_L_E_T_ <> '*' 
    AND SD1.D1_DOC = '000001617'
    AND SD1.D1_FILIAL = '01011021'
    AND NOT EXISTS (
        SELECT SBZ.BZ_COD 
        FROM [1_RAW].[SBZ_PROTHEUS] SBZ 
        WHERE SBZ.BZ_FILIAL = SD1.D1_FILIAL 
          AND SBZ.BZ_COD = SD1.D1_COD 
          AND SBZ.D_E_L_E_T_ = ' '
    );
